spring.data.mongodb.uri=mongodb+srv://lamgiabao73_db_user:5F7uk6t8HoGZD0aD@wdt.n2jlejk.mongodb.net/webbanhang?retryWrites=true&w=majority
jwt.secret=your_very_long_and_secure_secret_key_change_in_production_2026
cloudinary.cloud_name=dsa2vb0wo
cloudinary.api_key=283798679412981
cloudinary.api_secret=CceY-LAJc3oFFDERTZ_7cYOsfpU